### ISSUE TITLE
Cant view failures in uchiwa

### ISSUE THREAD

**Issue by benh57** [solarkennedy/sensu-shell-helper#12]
I had a sensu-shell-helper run fail. (i'm using it to trigger a cron'd database backup) It shows up on the main page of the uchiwa GUI, but when i click into it, its not listed on the right side.

Not sure if this is an issue with this script (probably not) but perhaps you'd know how to resolve it? Maybe I need to make a placeholder 'check' on the sensu server?

**Comment by solarkennedy** [comment]
These kind of events will not show up on the "checks" part of uchiwa, only the "events" page.

http://docs.uchiwa.io/en/latest/faq/faq/#my-standalone-check-does-not-appear-in-the-checks-view
