### ISSUE TITLE
Ruby Rewrite

### ISSUE THREAD

**Issue by solarkennedy** [solarkennedy/sensu-shell-helper#3]
Munging JSON in shell is lame.

If we are assuming that sensu is available, that means we have Ruby 2.0 available in /opt/sensu!

Lets rewrite this helper to simply use that. Optionally maybe just use the sensu plugin gem to get all the niceties of being a normal plugin, just an on-demand plugin called by cron or whatever.

**Comment by jaxxstorm** [comment]
Hey,

I had a bash at this. It's very very poor and I'm not a talented developer, so any feedback you might have (or time to improve it!) would be appreciated: https://github.com/jaxxstorm/sensu-wrapper

**Comment by solarkennedy** [comment]
Psha! I'm going to deprecate mine and just point to yours.
